import * as path from "node:path";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

function asTsStringArray(arr) {
    const lines = arr.map((s) => `  ${JSON.stringify(s)},`);
    return `[\n${lines.join("\n")}\n] as const`;
}

async function main() {
    const args = process.argv.slice(2);
    const inArg = args.find((a) => a.startsWith("--in="))?.slice("--in=".length);
    const outRootArg = args.find((a) => a.startsWith("--outRoot="))?.slice("--outRoot=".length);

    const inPath = path.resolve(process.cwd(), inArg ?? path.join("dota_dump", "index.json"));
    const outRoot = path.resolve(process.cwd(), outRootArg ?? path.join("src", "vscripts"));

    if (!existsSync(inPath)) {
        console.error(`❌ Не найден входной индекс: ${inPath}`);
        console.error("Сначала запустите: bun run dump:dota");
        process.exit(1);
    }

    const index = JSON.parse(await readFile(inPath, "utf8"));
    const heroes = (Array.isArray(index.heroes) ? index.heroes : []).filter((h) => h !== "npc_dota_hero_base");
    const abilities = Array.isArray(index.abilities) ? index.abilities : [];
    const items = Array.isArray(index.items) ? index.items : [];

    const heroesOut = path.join(outRoot, "heroes", "hero-pool.generated.ts");
    const abilitiesOut = path.join(outRoot, "abilities", "ability-pool.generated.ts");
    const itemsOut = path.join(outRoot, "items", "item-pool.generated.ts");

    await mkdir(path.dirname(heroesOut), { recursive: true });
    await mkdir(path.dirname(abilitiesOut), { recursive: true });
    await mkdir(path.dirname(itemsOut), { recursive: true });

    await writeFile(
        heroesOut,
        `// AUTO-GENERATED by bun run gen:dota-pools\n` +
            `// Source: ${path.relative(process.cwd(), inPath).replaceAll("\\\\", "/")}\n` +
            `export const HERO_POOL_GENERATED = ${asTsStringArray(heroes)};\n`,
        "utf8",
    );

    await writeFile(
        abilitiesOut,
        `// AUTO-GENERATED by bun run gen:dota-pools\n` +
            `// Source: ${path.relative(process.cwd(), inPath).replaceAll("\\\\", "/")}\n` +
            `export const ABILITY_POOL_GENERATED = ${asTsStringArray(abilities)};\n`,
        "utf8",
    );

    await writeFile(
        itemsOut,
        `// AUTO-GENERATED by bun run gen:dota-pools\n` +
            `// Source: ${path.relative(process.cwd(), inPath).replaceAll("\\\\", "/")}\n` +
            `export const ITEM_POOL_GENERATED = ${asTsStringArray(items)};\n`,
        "utf8",
    );

    console.log(`✓ Wrote: ${heroesOut}`);
    console.log(`✓ Wrote: ${abilitiesOut}`);
    console.log(`✓ Wrote: ${itemsOut}`);
    console.log(`✓ Counts: heroes=${heroes.length} abilities=${abilities.length} items=${items.length}`);
}

await main();


